services:
  rebalancer-service:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    env_file:
      - .env
    labels:
      prometheus.scrape: "true"
      prometheus.port: "8080"
    depends_on:
      kafka:
        condition: service_started
      init-kafka:
        condition: service_completed_successfully
      minio:
        condition: service_started
      init-minio:
        condition: service_completed_successfully
