services:
  contacts-worker:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      kafka:
        condition: service_started
      init-kafka:
        condition: service_completed_successfully
      minio:
        condition: service_started
      init-minio:
        condition: service_completed_successfully

