global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "docker-containers"
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        action: keep
        regex: true

      - source_labels: [__meta_docker_container_name, __meta_docker_container_label_prometheus_port]
        regex: /?([^/]+);(.+)
        replacement: $1:$2
        target_label: __address__

      - source_labels: [__meta_docker_container_name]
        target_label: container_name
