services:
  rebalancer-service:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ens-net
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
    labels:
      prometheus.scrape: "true"
      prometheus.port: "8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${PORT}/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    depends_on:
      kafka:
        condition: service_started
      init-kafka:
        condition: service_completed_successfully
      minio:
        condition: service_started
      init-minio:
        condition: service_completed_successfully
