services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123456789admin"
    ports:
      - "5433:5432"
    logging:
      driver: none
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./database/migrations/:/migrations
    command: [
      "-path",
      "/migrations",
      "-database",
      "postgres://user:123456789admin@postgres:5432/testdb?sslmode=disable",
      "up"
    ]
    restart: "no"

  test:
    image: golang:1.24.3
    volumes:
      - ./:/go/src/app
    working_dir: /go/src/app
    environment:
      TEST_DATABASE_URL: "postgres://user:123456789admin@postgres:5432/testdb?sslmode=disable"
      GO111MODULE: on
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    command: >
      sh -c "go mod download &&
      go test ./... -v -race -cover"
