services:
  sender-service:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 5
    env_file:
      - .env
    volumes:
      - ./tmp/sms-dev:/tmp/sms-dev
    labels:
      prometheus.scrape: "true"
      prometheus.port: "8080"
    depends_on:
      kafka:
        condition: service_started
      init-kafka:
        condition: service_completed_successfully
      minio:
        condition: service_started
      init-minio:
        condition: service_completed_successfully
