name: ci

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  lint-frontend:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run ESLint
        run: |
          cd frontend
          npm run lint

  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: Run lint
        run: |
          cd services
          make lint

  unit-test-backend:
    runs-on: ubuntu-latest
    needs: lint-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Run unit tests
        run: |
          cd services
          make unit-test

  integration-test-backend:
    runs-on: ubuntu-latest
    needs: unit-test-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Run integration tests
        run: |
          cd services
          make integration-test

  e2e-test:
    runs-on: ubuntu-latest
    needs: integration-test-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Run E2E Tests
        run: |
          cp .env.example .env
          make e2e-test
