name: contacts-worker-ci

on:
  push:
    branches: [ main ]
    paths:
      - "services/contacts-worker/**"
      - ".github/workflows/contacts-worker.yaml"

  pull_request:
    branches: [ main ]
    paths:
      - "services/contacts-worker/**"
      - ".github/workflows/contacts-worker.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          working-directory: services/contacts-worker

  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Run unit tests
        working-directory: services/contacts-worker
        run: |
          make unit-test

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Run integration tests
        working-directory: services/contacts-worker
        run: |
          make integration-test
