name: "contacts worker audit"

on:
  push:
    branches: [ main ]
    paths:
      - "contacts-worker/**"
      - ".github/workflows/contacts-worker.yaml"

  pull_request:
    branches: [ main ]
    paths:
      - "contacts-worker/**"
      - ".github/workflows/contacts-worker.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          working-directory: apiservice

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: run tests
        run: |
          cd contacts-worker
          go test ./... -v -race -cover
        env:
          DOCKER_BUILDKIT: 1