name: e2e-test

on:
  workflow_run:
    workflows:
      - api-service-ci
      - contacts-worker-ci
      - frontend-ci
      - notification-service-ci
      - rebalancer-service-ci
      - sender-service-ci
    types:
      - completed

jobs:
  e2e-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Run E2E Tests
        run: |
          cp .env.example .env
          make e2e-test
