name: rebalancer-service-ci

on:
  push:
    branches: [ main ]
    paths:
      - "services/rebalancer-service/**"
      - ".github/workflows/rebalancer-service.yaml"

  pull_request:
    branches: [ main ]
    paths:
      - "services/rebalancer-service/**"
      - ".github/workflows/rebalancer-service.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          working-directory: services/rebalancer-service

  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Run unit tests
        working-directory: services/rebalancer-service
        run: |
          go test ./... -timeout 60s

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Run integration tests
        working-directory: services/rebalancer-service
        run: |
          go test ./... -timeout 120s -tags=integration
